// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: nats_format.proto

package nats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UsersMethod — метод Tinkoff UsersService (только чтение).
type UsersMethod int32

const (
	UsersMethod_USERS_METHOD_UNSPECIFIED UsersMethod = 0
	UsersMethod_GET_ACCOUNTS             UsersMethod = 1
	UsersMethod_GET_MARGIN_ATTRIBUTES    UsersMethod = 2
	UsersMethod_GET_USER_TARIFF          UsersMethod = 3
	UsersMethod_GET_INFO                 UsersMethod = 4
	UsersMethod_GET_BANK_ACCOUNTS        UsersMethod = 5
	UsersMethod_GET_ACCOUNT_VALUES       UsersMethod = 6
)

// Enum value maps for UsersMethod.
var (
	UsersMethod_name = map[int32]string{
		0: "USERS_METHOD_UNSPECIFIED",
		1: "GET_ACCOUNTS",
		2: "GET_MARGIN_ATTRIBUTES",
		3: "GET_USER_TARIFF",
		4: "GET_INFO",
		5: "GET_BANK_ACCOUNTS",
		6: "GET_ACCOUNT_VALUES",
	}
	UsersMethod_value = map[string]int32{
		"USERS_METHOD_UNSPECIFIED": 0,
		"GET_ACCOUNTS":             1,
		"GET_MARGIN_ATTRIBUTES":    2,
		"GET_USER_TARIFF":          3,
		"GET_INFO":                 4,
		"GET_BANK_ACCOUNTS":        5,
		"GET_ACCOUNT_VALUES":       6,
	}
)

func (x UsersMethod) Enum() *UsersMethod {
	p := new(UsersMethod)
	*p = x
	return p
}

func (x UsersMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsersMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_format_proto_enumTypes[0].Descriptor()
}

func (UsersMethod) Type() protoreflect.EnumType {
	return &file_nats_format_proto_enumTypes[0]
}

func (x UsersMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UsersMethod.Descriptor instead.
func (UsersMethod) EnumDescriptor() ([]byte, []int) {
	return file_nats_format_proto_rawDescGZIP(), []int{0}
}

type UsersStatusKind int32

const (
	UsersStatusKind_USERS_STATUS_UNSPECIFIED UsersStatusKind = 0
	UsersStatusKind_ACCEPTED                 UsersStatusKind = 1 // задание принято в работу
	UsersStatusKind_DONE                     UsersStatusKind = 2 // задание выполнено
	UsersStatusKind_READY                    UsersStatusKind = 3 // данные опубликованы и готовы к чтению
	UsersStatusKind_FAILED                   UsersStatusKind = 4 // ошибка выполнения
)

// Enum value maps for UsersStatusKind.
var (
	UsersStatusKind_name = map[int32]string{
		0: "USERS_STATUS_UNSPECIFIED",
		1: "ACCEPTED",
		2: "DONE",
		3: "READY",
		4: "FAILED",
	}
	UsersStatusKind_value = map[string]int32{
		"USERS_STATUS_UNSPECIFIED": 0,
		"ACCEPTED":                 1,
		"DONE":                     2,
		"READY":                    3,
		"FAILED":                   4,
	}
)

func (x UsersStatusKind) Enum() *UsersStatusKind {
	p := new(UsersStatusKind)
	*p = x
	return p
}

func (x UsersStatusKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsersStatusKind) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_format_proto_enumTypes[1].Descriptor()
}

func (UsersStatusKind) Type() protoreflect.EnumType {
	return &file_nats_format_proto_enumTypes[1]
}

func (x UsersStatusKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UsersStatusKind.Descriptor instead.
func (UsersStatusKind) EnumDescriptor() ([]byte, []int) {
	return file_nats_format_proto_rawDescGZIP(), []int{1}
}

type IndicatorTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Interval      int32                  `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Time          int64                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`                                // DateTime64 передается как Int64 (Unix Timestamp)
	Open          float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`                               // Decimal64(9) → int64 (масштабированный)
	High          float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`                               // Decimal64(9) → int64 (масштабированный)
	Low           float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`                                 // Decimal64(9) → int64 (масштабированный)
	Close         float64                `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`                             // Decimal64(9) → int64 (масштабированный)
	Volume        int64                  `protobuf:"varint,8,opt,name=volume,proto3" json:"volume,omitempty"`                            // Int64
	VolumeBuy     int64                  `protobuf:"varint,9,opt,name=volume_buy,json=volumeBuy,proto3" json:"volume_buy,omitempty"`     // Int64
	VolumeSell    int64                  `protobuf:"varint,10,opt,name=volume_sell,json=volumeSell,proto3" json:"volume_sell,omitempty"` // Int64
	CandleSource  int32                  `protobuf:"varint,11,opt,name=candle_source,json=candleSource,proto3" json:"candle_source,omitempty"`
	IsComplete    bool                   `protobuf:"varint,12,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndicatorTask) Reset() {
	*x = IndicatorTask{}
	mi := &file_nats_format_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicatorTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicatorTask) ProtoMessage() {}

func (x *IndicatorTask) ProtoReflect() protoreflect.Message {
	mi := &file_nats_format_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicatorTask.ProtoReflect.Descriptor instead.
func (*IndicatorTask) Descriptor() ([]byte, []int) {
	return file_nats_format_proto_rawDescGZIP(), []int{0}
}

func (x *IndicatorTask) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *IndicatorTask) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *IndicatorTask) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *IndicatorTask) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *IndicatorTask) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *IndicatorTask) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *IndicatorTask) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *IndicatorTask) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *IndicatorTask) GetVolumeBuy() int64 {
	if x != nil {
		return x.VolumeBuy
	}
	return 0
}

func (x *IndicatorTask) GetVolumeSell() int64 {
	if x != nil {
		return x.VolumeSell
	}
	return 0
}

func (x *IndicatorTask) GetCandleSource() int32 {
	if x != nil {
		return x.CandleSource
	}
	return 0
}

func (x *IndicatorTask) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

// HistoricCandleLoadTask — задание на догрузку исторических свечей.
// Один NATS-subject = один инструмент: TrB.HistoricCandle.Task.{uid}.{interval}.
// В uid достаточно одного значения (первое); интервал дублирует токен subject.
type HistoricCandleLoadTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           []string               `protobuf:"bytes,1,rep,name=uid,proto3" json:"uid,omitempty"`
	Interval      int32                  `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"` // значение pb.CandleInterval; 0 = 1 минута
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricCandleLoadTask) Reset() {
	*x = HistoricCandleLoadTask{}
	mi := &file_nats_format_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricCandleLoadTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricCandleLoadTask) ProtoMessage() {}

func (x *HistoricCandleLoadTask) ProtoReflect() protoreflect.Message {
	mi := &file_nats_format_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricCandleLoadTask.ProtoReflect.Descriptor instead.
func (*HistoricCandleLoadTask) Descriptor() ([]byte, []int) {
	return file_nats_format_proto_rawDescGZIP(), []int{1}
}

func (x *HistoricCandleLoadTask) GetUid() []string {
	if x != nil {
		return x.Uid
	}
	return nil
}

func (x *HistoricCandleLoadTask) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                     //UID инструмента.
	Time          *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=time,proto3" json:"time,omitempty"`                                  //Время сделки в часовом поясе UTC по времени биржи.
	Figi          string                 `protobuf:"bytes,3,opt,name=figi,proto3" json:"figi,omitempty"`                                   //FIGI-идентификатор инструмента.
	Direction     int32                  `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`                        //Направление сделки.
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`                               //Цена за 1 инструмент. Чтобы получить стоимость лота, нужно умножить на лотность инструмента. [Подробнее про перевод цен в валюту](./faq_marketdata/#_15).
	Quantity      int64                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`                          //Количество лотов.
	TradeSource   int32                  `protobuf:"varint,7,opt,name=trade_source,json=tradeSource,proto3" json:"trade_source,omitempty"` //Тип источника сделки.
	Ticker        string                 `protobuf:"bytes,8,opt,name=ticker,proto3" json:"ticker,omitempty"`                               //Тикер инструмента.
	ClassCode     string                 `protobuf:"bytes,9,opt,name=class_code,json=classCode,proto3" json:"class_code,omitempty"`        //Класс-код (секция торгов).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_nats_format_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_nats_format_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_nats_format_proto_rawDescGZIP(), []int{2}
}

func (x *Trade) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Trade) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Trade) GetFigi() string {
	if x != nil {
		return x.Figi
	}
	return ""
}

func (x *Trade) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetTradeSource() int32 {
	if x != nil {
		return x.TradeSource
	}
	return 0
}

func (x *Trade) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Trade) GetClassCode() string {
	if x != nil {
		return x.ClassCode
	}
	return ""
}

// UsersTask — запрос данных UsersService.
// Subject: TrB.Users.Task.{method}, например TrB.Users.Task.GetAccounts.
// method в subject — источник истины; поле method в теле — запасной вариант.
// task_id задаёт инициатор (чтобы слушать Status.{task_id}.*); если пусто — воркер сгенерирует UUID.
type UsersTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Method        UsersMethod            `protobuf:"varint,2,opt,name=method,proto3,enum=nats.UsersMethod" json:"method,omitempty"`
	AccountStatus int32                  `protobuf:"varint,3,opt,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty"` // GetAccounts: pb.AccountStatus; 0 = ACCOUNT_STATUS_ALL
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`              // GetMarginAttributes; пусто = INVEST_ACCOUNT_ID
	Accounts      []string               `protobuf:"bytes,5,rep,name=accounts,proto3" json:"accounts,omitempty"`                                 // GetAccountValues
	Values        []int32                `protobuf:"varint,6,rep,packed,name=values,proto3" json:"values,omitempty"`                             // GetAccountValues: pb.AccountValue
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersTask) Reset() {
	*x = UsersTask{}
	mi := &file_nats_format_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersTask) ProtoMessage() {}

func (x *UsersTask) ProtoReflect() protoreflect.Message {
	mi := &file_nats_format_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersTask.ProtoReflect.Descriptor instead.
func (*UsersTask) Descriptor() ([]byte, []int) {
	return file_nats_format_proto_rawDescGZIP(), []int{3}
}

func (x *UsersTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UsersTask) GetMethod() UsersMethod {
	if x != nil {
		return x.Method
	}
	return UsersMethod_USERS_METHOD_UNSPECIFIED
}

func (x *UsersTask) GetAccountStatus() int32 {
	if x != nil {
		return x.AccountStatus
	}
	return 0
}

func (x *UsersTask) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UsersTask) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *UsersTask) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// UsersStatus — push-уведомление о стадии задания (Core NATS, без JetStream).
// Subject: TrB.Users.Status.{task_id}.{accepted|ready|done|failed}
// Слушатель должен подписаться до публикации задания, иначе уведомление пропадёт.
type UsersStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Method        UsersMethod            `protobuf:"varint,2,opt,name=method,proto3,enum=nats.UsersMethod" json:"method,omitempty"`
	Kind          UsersStatusKind        `protobuf:"varint,3,opt,name=kind,proto3,enum=nats.UsersStatusKind" json:"kind,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersStatus) Reset() {
	*x = UsersStatus{}
	mi := &file_nats_format_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersStatus) ProtoMessage() {}

func (x *UsersStatus) ProtoReflect() protoreflect.Message {
	mi := &file_nats_format_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersStatus.ProtoReflect.Descriptor instead.
func (*UsersStatus) Descriptor() ([]byte, []int) {
	return file_nats_format_proto_rawDescGZIP(), []int{4}
}

func (x *UsersStatus) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UsersStatus) GetMethod() UsersMethod {
	if x != nil {
		return x.Method
	}
	return UsersMethod_USERS_METHOD_UNSPECIFIED
}

func (x *UsersStatus) GetKind() UsersStatusKind {
	if x != nil {
		return x.Kind
	}
	return UsersStatusKind_USERS_STATUS_UNSPECIFIED
}

func (x *UsersStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UsersData — ответ Tinkoff. payload — protobuf соответствующего *Response из invest-go.
// Subject: TrB.Users.Data.{method}.{task_id}
type UsersData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Method        UsersMethod            `protobuf:"varint,2,opt,name=method,proto3,enum=nats.UsersMethod" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersData) Reset() {
	*x = UsersData{}
	mi := &file_nats_format_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersData) ProtoMessage() {}

func (x *UsersData) ProtoReflect() protoreflect.Message {
	mi := &file_nats_format_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersData.ProtoReflect.Descriptor instead.
func (*UsersData) Descriptor() ([]byte, []int) {
	return file_nats_format_proto_rawDescGZIP(), []int{5}
}

func (x *UsersData) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UsersData) GetMethod() UsersMethod {
	if x != nil {
		return x.Method
	}
	return UsersMethod_USERS_METHOD_UNSPECIFIED
}

func (x *UsersData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_nats_format_proto protoreflect.FileDescriptor

const file_nats_format_proto_rawDesc = "" +
	"\n" +
	"\x11nats_format.proto\x12\x04nats\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n" +
	"\rIndicatorTask\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\x05R\binterval\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x03R\x04time\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\b \x01(\x03R\x06volume\x12\x1d\n" +
	"\n" +
	"volume_buy\x18\t \x01(\x03R\tvolumeBuy\x12\x1f\n" +
	"\vvolume_sell\x18\n" +
	" \x01(\x03R\n" +
	"volumeSell\x12#\n" +
	"\rcandle_source\x18\v \x01(\x05R\fcandleSource\x12\x1f\n" +
	"\vis_complete\x18\f \x01(\bR\n" +
	"isComplete\"F\n" +
	"\x16HistoricCandleLoadTask\x12\x10\n" +
	"\x03uid\x18\x01 \x03(\tR\x03uid\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\x05R\binterval\"\x87\x02\n" +
	"\x05Trade\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12.\n" +
	"\x04time\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04figi\x18\x03 \x01(\tR\x04figi\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\x05R\tdirection\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\x12!\n" +
	"\ftrade_source\x18\a \x01(\x05R\vtradeSource\x12\x16\n" +
	"\x06ticker\x18\b \x01(\tR\x06ticker\x12\x1d\n" +
	"\n" +
	"class_code\x18\t \x01(\tR\tclassCode\"\xc9\x01\n" +
	"\tUsersTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12)\n" +
	"\x06method\x18\x02 \x01(\x0e2\x11.nats.UsersMethodR\x06method\x12%\n" +
	"\x0eaccount_status\x18\x03 \x01(\x05R\raccountStatus\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12\x1a\n" +
	"\baccounts\x18\x05 \x03(\tR\baccounts\x12\x16\n" +
	"\x06values\x18\x06 \x03(\x05R\x06values\"\x92\x01\n" +
	"\vUsersStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12)\n" +
	"\x06method\x18\x02 \x01(\x0e2\x11.nats.UsersMethodR\x06method\x12)\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x15.nats.UsersStatusKindR\x04kind\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"i\n" +
	"\tUsersData\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12)\n" +
	"\x06method\x18\x02 \x01(\x0e2\x11.nats.UsersMethodR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload*\xaa\x01\n" +
	"\vUsersMethod\x12\x1c\n" +
	"\x18USERS_METHOD_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fGET_ACCOUNTS\x10\x01\x12\x19\n" +
	"\x15GET_MARGIN_ATTRIBUTES\x10\x02\x12\x13\n" +
	"\x0fGET_USER_TARIFF\x10\x03\x12\f\n" +
	"\bGET_INFO\x10\x04\x12\x15\n" +
	"\x11GET_BANK_ACCOUNTS\x10\x05\x12\x16\n" +
	"\x12GET_ACCOUNT_VALUES\x10\x06*^\n" +
	"\x0fUsersStatusKind\x12\x1c\n" +
	"\x18USERS_STATUS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bACCEPTED\x10\x01\x12\b\n" +
	"\x04DONE\x10\x02\x12\t\n" +
	"\x05READY\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04B\tZ\a./;natsb\x06proto3"

var (
	file_nats_format_proto_rawDescOnce sync.Once
	file_nats_format_proto_rawDescData []byte
)

func file_nats_format_proto_rawDescGZIP() []byte {
	file_nats_format_proto_rawDescOnce.Do(func() {
		file_nats_format_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nats_format_proto_rawDesc), len(file_nats_format_proto_rawDesc)))
	})
	return file_nats_format_proto_rawDescData
}

var file_nats_format_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nats_format_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nats_format_proto_goTypes = []any{
	(UsersMethod)(0),               // 0: nats.UsersMethod
	(UsersStatusKind)(0),           // 1: nats.UsersStatusKind
	(*IndicatorTask)(nil),          // 2: nats.IndicatorTask
	(*HistoricCandleLoadTask)(nil), // 3: nats.HistoricCandleLoadTask
	(*Trade)(nil),                  // 4: nats.Trade
	(*UsersTask)(nil),              // 5: nats.UsersTask
	(*UsersStatus)(nil),            // 6: nats.UsersStatus
	(*UsersData)(nil),              // 7: nats.UsersData
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_nats_format_proto_depIdxs = []int32{
	8, // 0: nats.Trade.time:type_name -> google.protobuf.Timestamp
	0, // 1: nats.UsersTask.method:type_name -> nats.UsersMethod
	0, // 2: nats.UsersStatus.method:type_name -> nats.UsersMethod
	1, // 3: nats.UsersStatus.kind:type_name -> nats.UsersStatusKind
	0, // 4: nats.UsersData.method:type_name -> nats.UsersMethod
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_nats_format_proto_init() }
func file_nats_format_proto_init() {
	if File_nats_format_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nats_format_proto_rawDesc), len(file_nats_format_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nats_format_proto_goTypes,
		DependencyIndexes: file_nats_format_proto_depIdxs,
		EnumInfos:         file_nats_format_proto_enumTypes,
		MessageInfos:      file_nats_format_proto_msgTypes,
	}.Build()
	File_nats_format_proto = out.File
	file_nats_format_proto_goTypes = nil
	file_nats_format_proto_depIdxs = nil
}
