jetstream {
    enabled: true
}

port: 4222
http_port: 8222
server_name: "nats-server"

system_account: "sys"

accounts {
  sys {
    users: [
      { 
        user: "sys", 
        password: "syspass",
        permissions: {
          publish: { allow: ["$SYS.>", ">"] }
          subscribe: { allow: ["$SYS.>", ">"] }
        }
      }
    ]
    
    exports: [
      { service: "$SYS.REQ.ACCOUNT.*" }
      { service: "$SYS.REQ.SERVER.PING" }
      { service: "$SYS.REQ.SERVER.PING.JSZ" }
      { service: "$SYS.REQ.STATS.ZOOM.>" }
      { service: "$SYS.REQ.STREAM.INFO.*" }
      { service: "$SYS.REQ.CONSUMER.INFO.*" }
      { stream: "$SYS.ACCOUNT.>" }
      { stream: "$SYS.SERVER.>" }
    ]
  }
}